//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pryXMLChanger.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("pryXMLChanger.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Icon similar a (Icono).
        /// </summary>
        internal static System.Drawing.Icon AppIco {
            get {
                object obj = ResourceManager.GetObject("AppIco", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;types&gt;
        ///    &lt;type name=&quot;ACOGOptic&quot;&gt;
        ///        &lt;nominal&gt;12&lt;/nominal&gt;
        ///        &lt;lifetime&gt;14400&lt;/lifetime&gt;
        ///        &lt;restock&gt;900&lt;/restock&gt;
        ///        &lt;min&gt;8&lt;/min&gt;
        ///        &lt;quantmin&gt;-1&lt;/quantmin&gt;
        ///        &lt;quantmax&gt;-1&lt;/quantmax&gt;
        ///        &lt;cost&gt;100&lt;/cost&gt;
        ///        &lt;flags count_in_cargo=&quot;0&quot; count_in_hoarder=&quot;0&quot; count_in_map=&quot;1&quot; count_in_player=&quot;0&quot; crafted=&quot;0&quot; deloot=&quot;0&quot;/&gt;
        ///        &lt;category name=&quot;weapons&quot;/&gt;
        ///        &lt;usage name=&quot;Military&quot;/&gt;
        ///    &lt;/type&gt;
        ///    &lt;type name=&quot;A [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string original_types {
            get {
                return ResourceManager.GetString("original_types", resourceCulture);
            }
        }
    }
}
